"""table updates

Revision ID: 609e48e72cf9
Revises: 10d05234fc87
Create Date: 2024-09-24 11:55:05.815206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '609e48e72cf9'
down_revision: Union[str, None] = '10d05234fc87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('task_status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'task_status')
    # ### end Alembic commands ###
