"""table updates

Revision ID: ec1ef8adb725
Revises: 609e48e72cf9
Create Date: 2024-09-24 12:26:38.728155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec1ef8adb725'
down_revision: Union[str, None] = '609e48e72cf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_files_id', table_name='files')
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.create_index('ix_files_id', 'files', ['id'], unique=False)
    # ### end Alembic commands ###
